# Generated by Django 5.2 on 2025-04-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
