# Generated by Django 5.2 on 2025-04-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('celulose_virgem_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('gel_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('tnt_filtrante_780_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('fita_adesiva_tape_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('elastico_elastano_lycra_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('barreira_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('polietileno_filme_780_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('hot_melt_const_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
        ),
    ]
