# Generated by Django 5.2 on 2025-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(default='', max_length=100)),
                ('celulose_virgem_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Celulose virgem (R$)')),
                ('gel_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Gel (R$)')),
                ('tnt_filtrante_780_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='TNT filtrante 780 (R$)')),
                ('fita_adesiva_tape_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Fita adesiva tape (R$)')),
                ('elastico_elastano_lycra_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Elástico elástano lycra (R$)')),
                ('barreira_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Barreira (R$)')),
                ('polietileno_filme_780_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Polietileno filme 780 (R$)')),
                ('hot_melt_const_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Hot melt const (R$)')),
            ],
        ),
    ]
