# Generated by Django 5.2 on 2025-04-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='elastico_elastano_lycra_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Elástico - Elastano - Lycra (R$)'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='fita_adesiva_tape_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Fita adesiva - Tape (R$)'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='hot_melt_const_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Hot-Melt Construção (R$)'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='polietileno_filme_780_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Polietileno - Filme - 780mm (R$)'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='tnt_filtrante_780_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='TNT - filtrante 780mm (R$)'),
        ),
    ]
