# Generated by Django 5.2 on 2025-04-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bellafral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('bellafral', 'Bellafral'), ('big_confort', 'Big Confort'), ('basic_mille', 'Basic Mille')], default='Bellafral', max_length=100)),
                ('identificador', models.CharField(max_length=100)),
                ('tamanho', models.CharField(choices=[('XG', 'XG'), ('G', 'G'), ('M', 'M')], max_length=2)),
                ('celulose_virgem', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Celulose virgem (Kg)')),
                ('gel', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Gel (Kg)')),
                ('tnt_filtrante_780', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='TNT - Filtrante - 780mm (m2)')),
                ('fita_adesiva_tape', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Fita adesiva - Tape (Kg)')),
                ('elastico_elastano_lycra', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Elástico - Elastano - Lycra (Kg)')),
                ('barreira', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Barreira (m2)')),
                ('polietileno_filme_780', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Polietileno - Filme - 780mm (Kg)')),
                ('hot_melt_const', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Hot-Melt Construção (Kg)')),
            ],
        ),
        migrations.CreateModel(
            name='Simulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fralda', models.JSONField(default=dict)),
                ('costs', models.JSONField(default=dict)),
                ('simulation', models.JSONField(default=dict)),
                ('costs_object', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='costs.costs')),
                ('fralda_object', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bellafral.bellafral')),
            ],
        ),
    ]
