# Generated by Django 5.2 on 2025-04-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bellafral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tamanho', models.CharField(choices=[('XG', 'XG'), ('G', 'G'), ('M', 'M')], max_length=2)),
                ('Celulose virgem', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Gel', models.DecimalField(decimal_places=4, max_digits=10)),
                ('TNT - Filtrante - 780mm', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Fita adesiva - Tape', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Elástico - Elastano - Lycra', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Barreira', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Polietileno - Filme - 780mm', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Hot-Melt Construção', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
