# Generated by Django 5.2 on 2025-04-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bellafral', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bellafral',
            old_name='Barreira',
            new_name='Barreira (m2)',
        ),
        migrations.RenameField(
            model_name='bellafral',
            old_name='Celulose virgem',
            new_name='Celulose virgem (Kg)',
        ),
        migrations.RenameField(
            model_name='bellafral',
            old_name='Elástico - Elastano - Lycra',
            new_name='Elástico - Elastano - Lycra (Kg)',
        ),
        migrations.RenameField(
            model_name='bellafral',
            old_name='Fita adesiva - Tape',
            new_name='Fita adesiva - Tape (Kg)',
        ),
        migrations.RenameField(
            model_name='bellafral',
            old_name='Gel',
            new_name='Gel (Kg)',
        ),
        migrations.RenameField(
            model_name='bellafral',
            old_name='Hot-Melt Construção',
            new_name='Hot-Melt Construção (Kg)',
        ),
        migrations.RenameField(
            model_name='bellafral',
            old_name='Polietileno - Filme - 780mm',
            new_name='Polietileno - Filme - 780mm (Kg)',
        ),
        migrations.RenameField(
            model_name='bellafral',
            old_name='TNT - Filtrante - 780mm',
            new_name='TNT - Filtrante - 780mm (m2)',
        ),
    ]
