# Generated by Django 5.2 on 2025-04-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellafral', '0001_initial'),
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bellafral',
            name='modelo',
            field=models.CharField(choices=[('Bellafral', 'Bellafral'), ('Big Confort', 'Big Confort'), ('Basic Mille', 'Basic Mille')], default='Bellafral', max_length=100),
        ),
        migrations.AlterField(
            model_name='simulations',
            name='costs_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='costs.costs'),
        ),
        migrations.AlterField(
            model_name='simulations',
            name='fralda_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bellafral.bellafral'),
        ),
    ]
