# Generated by Django 5.2 on 2025-04-08 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellafral', '0002_alter_bellafral_modelo_and_more'),
        ('costs', '0002_alter_costs_elastico_elastano_lycra_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulations',
            name='costs_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='costs.costs'),
        ),
        migrations.AlterField(
            model_name='simulations',
            name='fralda_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bellafral.bellafral'),
        ),
    ]
