# Generated by Django 5.2 on 2025-04-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellafral', '0002_rename_barreira_bellafral_barreira_m2__and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bellafral',
            name='Barreira (m2)',
        ),
        migrations.RemoveField(
            model_name='bellafral',
            name='Celulose virgem (Kg)',
        ),
        migrations.RemoveField(
            model_name='bellafral',
            name='Elástico - Elastano - Lycra (Kg)',
        ),
        migrations.RemoveField(
            model_name='bellafral',
            name='Fita adesiva - Tape (Kg)',
        ),
        migrations.RemoveField(
            model_name='bellafral',
            name='Gel (Kg)',
        ),
        migrations.RemoveField(
            model_name='bellafral',
            name='Hot-Melt Construção (Kg)',
        ),
        migrations.RemoveField(
            model_name='bellafral',
            name='Polietileno - Filme - 780mm (Kg)',
        ),
        migrations.RemoveField(
            model_name='bellafral',
            name='TNT - Filtrante - 780mm (m2)',
        ),
        migrations.AddField(
            model_name='bellafral',
            name='barreira',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Barreira (m2)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='celulose_virgem',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Celulose virgem (Kg)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='elastico_elastano_lycra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Elástico - Elastano - Lycra (Kg)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='fita_adesiva_tape',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Fita adesiva - Tape (Kg)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='gel',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Gel (Kg)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='hot_melt_const',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Hot-Melt Construção (Kg)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='polietileno_filme_780',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Polietileno - Filme - 780mm (Kg)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='tnt_filtrante_780',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='TNT - Filtrante - 780mm (m2)'),
        ),
    ]
