# Generated by Django 5.2 on 2025-04-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bellafral', '0003_alter_simulations_costs_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulations',
            name='costs',
        ),
        migrations.RemoveField(
            model_name='simulations',
            name='fralda',
        ),
        migrations.RemoveField(
            model_name='simulations',
            name='simulation',
        ),
    ]
