# Generated by Django 5.2 on 2025-04-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellafral', '0003_remove_bellafral_barreira_m2__and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation', models.JSONField()),
            ],
        ),
    ]
