# Generated by Django 5.2 on 2025-04-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellafral', '0004_remove_simulations_costs_remove_simulations_fralda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bellafral',
            name='barreira_total_unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo unitário da barreira (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='celulose_virgem_total_unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo unitário da celulose virgem (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='elastico_elastano_lycra_total_unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo unitário do elástico - Elastano - Lycra (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='fita_adesiva_tape_total_unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo unitário da fita adesiva - Tape (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='gel_total_unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo unitário do gel (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='hot_melt_const_total_unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo unitário do Hot-Melt Construção (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='polietileno_filme_780_total_unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo unitário do polietileno - Filme - 780mm (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='tnt_filtrante_780_total_unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo unitário do TNT - Filtrante - 780mm (R$)'),
        ),
    ]
