# Generated by Django 5.2 on 2025-04-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellafral', '0004_simulations'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulations',
            name='fralda',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='simulations',
            name='stock',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='simulations',
            name='simulation',
            field=models.JSONField(default=dict),
        ),
    ]
