# Generated by Django 5.2 on 2025-04-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellafral', '0006_alter_bellafral_barreira_total_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bellafral',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Custo total (R$)'),
        ),
    ]
