# Generated by Django 5.2 on 2025-04-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellafral', '0007_bellafral_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bellafral',
            name='comissao',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Comissão (%)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='custo_pacote',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Custo do pacote (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='custo_unitario_final',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Custo unitário final (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='embalagem',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Embalagem (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='frete',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Frete (%)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='impostos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Impostos (%)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='margem_contribuicao',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Margem de contribuição (%)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Preço de venda (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='preco_venda_st',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Preço de venda com ST (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='preco_venda_st_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Preço de venda unitário com ST (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='preco_venda_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Preço de venda unitário (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='qtd_p_pacote',
            field=models.IntegerField(default=0, verbose_name='Quantidade de peças por pacote'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='saco_fardos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Saco para fardos (R$)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='st',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='ST (%)'),
        ),
    ]
