# Generated by Django 5.2 on 2025-04-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellafral', '0008_bellafral_comissao_bellafral_custo_pacote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bellafral',
            name='saco_fardos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Saco para fardos/Encarte (R$)'),
        ),
    ]
