# Generated by Django 5.2 on 2025-04-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellafral', '0009_alter_bellafral_saco_fardos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bellafral',
            name='identificador',
            field=models.CharField(max_length=100, verbose_name='Identificador'),
        ),
    ]
