# Generated by Django 5.2 on 2025-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellafral', '0010_alter_bellafral_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='bellafral',
            name='loss_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Perdas (%)'),
        ),
        migrations.AddField(
            model_name='bellafral',
            name='total_cost_with_loss',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Custo total com perdas (R$)'),
        ),
    ]
